---
abstract: 'memoise expression on first execution'
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  Devel::CallChecker: 0.003
  ExtUtils::CBuilder: 0.15
  IO::File: 1.03
  Module::Build: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0
  perl: 5.006
  strict: 0
  warnings: 0
dynamic_config: 0
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Memoize-Once
provides:
  Memoize::Once:
    file: lib/Memoize/Once.pm
    version: 0
requires:
  Devel::CallChecker: 0.003
  Exporter: 0
  XSLoader: 0
  parent: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.000
